<?php

namespace Database\Seeders;

use App\Enums\Template;
use App\Models\Category;
use App\Models\Menu;
use Illuminate\Database\Seeder;

class MenuImportSeeder extends Seeder
{
    /**
     * Import menu data from:
     * - MENU CAFE 1912.xlsx
     * - MENU BOGA.xlsx
     * - MENU PASTERY.xlsx
     *
     * Setiap kategori berasal dari satu file sumber saja (tidak ada kategori
     * yang overlap antar file), jadi pemetaan kategori -> outlet di bawah ini
     * deterministik berdasarkan file asalnya.
     */
    private const CATEGORY_TEMPLATE_MAP = [
        // MENU CAFE 1912.xlsx (kolom "Sumber": Cafe 1912 - ...)
        'Capcay' => Template::Cafe1912,
        'Pasta' => Template::Cafe1912,
        'Rice Bowl' => Template::Cafe1912,
        'Steak' => Template::Cafe1912,
        'Main Course' => Template::Cafe1912,
        'Fried Rice' => Template::Cafe1912,
        'Appetizer' => Template::Cafe1912,
        'Dessert' => Template::Cafe1912,
        'Sandwich' => Template::Cafe1912,
        'Other' => Template::Cafe1912,
        'Milk Blend' => Template::Cafe1912,
        'Milk Base' => Template::Cafe1912,
        'Mocktail' => Template::Cafe1912,
        'Signature' => Template::Cafe1912,
        'Espresso Base' => Template::Cafe1912,
        'Manual Brew' => Template::Cafe1912,
        'Tea Base' => Template::Cafe1912,
        'Coffee Milk' => Template::Cafe1912,
        // MENU BOGA.xlsx (seluruh isi file)
        'Bakso Malang' => Template::Foodcourt,
        'Mie Ayam' => Template::Foodcourt,
        'Indomie Menu' => Template::Foodcourt,
        'Snack' => Template::Foodcourt,
        'Minuman' => Template::Foodcourt,
        'Drink Corner' => Template::Foodcourt,
        // MENU PASTERY.xlsx (seluruh isi file)
        'Pastry' => Template::PastryBakery,
    ];

    public function run(): void
    {
        $data = [
            'Capcay' => [
                ['name' => 'Vegetable Capcay', 'price' => 25000],
                ['name' => 'Chicken Capcay', 'price' => 28000],
                ['name' => 'Seafood Capcay', 'price' => 30000],
                ['name' => 'Meatball Capcay', 'price' => 30000],
                ['name' => 'Sausage Capcay', 'price' => 28000],
            ],
            'Pasta' => [
                ['name' => 'Spaghetti Carbonara', 'price' => 22000],
                ['name' => 'Spaghetti Bolognese', 'price' => 22000],
                ['name' => 'Aglio Olio With Chicken', 'price' => 22000],
                ['name' => 'Aglio Olio With Beef', 'price' => 25000],
                ['name' => 'Aglio Olio With Seafood', 'price' => 25000],
            ],
            'Rice Bowl' => [
                ['name' => 'Chicken Katsu', 'price' => 25000],
                ['name' => 'Rice Bowl Chicken Pop', 'price' => 25000],
                ['name' => 'Rice Bowl Beef Sambal Matah', 'price' => 27000],
            ],
            'Steak' => [
                ['name' => 'Chicken Crispy Steak', 'price' => 30000],
                ['name' => 'Beef Crispy Steak', 'price' => 35000],
                ['name' => 'Italian Grill Steak', 'price' => 30000],
                ['name' => 'Tenderloin Steak', 'price' => 45000],
                ['name' => 'Sirloin Steak', 'price' => 45000],
                ['name' => 'Grilled Sausage', 'price' => 18000],
            ],
            'Main Course' => [
                ['name' => 'Fried Chicken Ala Cafe', 'price' => 20000],
                ['name' => 'Fried Chicken With Mozarella', 'price' => 23000],
                ['name' => 'Sate Taichan', 'price' => 25000],
                ['name' => 'Special Noodle', 'price' => 22000],
                ['name' => 'Special Meatball', 'price' => 25000],
                ['name' => 'Sate Sawah 1912', 'price' => 35000],
                ['name' => 'Sate Jamur', 'price' => 24000],
            ],
            'Fried Rice' => [
                ['name' => 'Teri Fried Rice', 'price' => 20000],
                ['name' => 'Chicken Fried Rice', 'price' => 25000],
                ['name' => 'Seafood Fried Rice', 'price' => 27000],
                ['name' => 'Rendang Beef Fried Rice', 'price' => 27000],
                ['name' => 'Kari Beef Fried Rice', 'price' => 27000],
            ],
            'Appetizer' => [
                ['name' => 'Original French Fries', 'price' => 15000],
                ['name' => 'Onion Ring', 'price' => 15000],
                ['name' => 'Brocoli Crispy', 'price' => 16000],
                ['name' => 'Enoki Crispy', 'price' => 18000],
                ['name' => 'Salad Roll', 'price' => 35000],
                ['name' => 'Dimsum', 'price' => 18000],
                ['name' => 'Grilled Sausage', 'price' => 18000],
                ['name' => 'Korean Spicy Wings', 'price' => 22000],
                ['name' => 'Snack Platter 1912', 'price' => 25000],
                ['name' => 'Salad Sayur', 'price' => 35000],
            ],
            'Dessert' => [
                ['name' => 'Banana Crispy', 'price' => 15000],
                ['name' => 'Banana Grill', 'price' => 15000],
                ['name' => 'Toasted Bread', 'price' => 13000],
                ['name' => 'Waffle', 'price' => 25000],
                ['name' => 'Puding Purin', 'price' => 10000],
            ],
            'Sandwich' => [
                ['name' => 'Sandwich Egg', 'price' => 15000],
                ['name' => 'Sandwich Sausage', 'price' => 15000],
                ['name' => 'Hungarian Sandwich', 'price' => 20000],
                ['name' => 'Crispy Sandwich', 'price' => 18000],
            ],
            'Other' => [
                ['name' => 'Extra Rice', 'price' => 4000],
                ['name' => 'Extra Sauce/Sambal', 'price' => 3000],
                ['name' => 'Extra Egg', 'price' => 4000],
            ],
            'Milk Blend' => [
                ['name' => 'Strawberry Ice Blend', 'price' => 16000],
                ['name' => 'Chocoberry Ice Blend', 'price' => 18000],
                ['name' => 'Choconut Ice Blend', 'price' => 20000],
            ],
            'Milk Base' => [
                ['name' => 'Chocolate', 'price' => 15000],
                ['name' => 'Redvelvet', 'price' => 15000],
                ['name' => 'Matcha Latte', 'price' => 22000],
                ['name' => 'Choco Flavour', 'price' => 20000],
                ['name' => 'Matcha Berry Latte', 'price' => 25000],
            ],
            'Mocktail' => [
                ['name' => 'Lemon Mocktail', 'price' => 16000],
                ['name' => 'Strawberry Mocktail', 'price' => 16000],
                ['name' => 'Orange Mocktail', 'price' => 16000],
                ['name' => 'Lychee Mocktail', 'price' => 16000],
            ],
            'Signature' => [
                ['name' => 'Lemon Coffee 1912', 'price' => 18000],
                ['name' => 'Pineapple Coffee 1912', 'price' => 18000],
                ['name' => 'Peach Coffee 1912', 'price' => 18000],
                ['name' => 'Klepon Latte 1912', 'price' => 20000],
                ['name' => 'Turmeric Orange 1912', 'price' => 20000],
                ['name' => 'Banana Klepon Latte 1912', 'price' => 25000],
            ],
            'Espresso Base' => [
                ['name' => 'Espresso', 'price' => 13000],
                ['name' => 'Cappuccino', 'price' => 22000],
                ['name' => 'Cafe Latte', 'price' => 20000],
                ['name' => 'Americano', 'price' => 15000],
                ['name' => 'Cafe Mocha', 'price' => 22000],
                ['name' => 'Flavor Cafe Latte', 'price' => 22000],
            ],
            'Manual Brew' => [
                ['name' => 'Tubruk Hot', 'price' => 15000],
                ['name' => 'Vietnam Drip', 'price' => 17000],
                ['name' => 'V60', 'price' => 20000],
            ],
            'Tea Base' => [
                ['name' => 'Black Tea', 'price' => 8000],
                ['name' => 'Lemon Tea', 'price' => 10000],
                ['name' => 'Strawberry Tea', 'price' => 12000],
                ['name' => 'Lychee Tea', 'price' => 12000],
                ['name' => 'Lemongrass Tea', 'price' => 12000],
                ['name' => 'Peach Tea', 'price' => 12000],
            ],
            'Coffee Milk' => [
                ['name' => 'Original Coffee Milk', 'price' => 18000],
                ['name' => 'Palm Sugar Coffee Milk', 'price' => 20000],
                ['name' => 'Banana Coffee Milk', 'price' => 22000],
                ['name' => 'Popcorn Coffee Milk', 'price' => 22000],
                ['name' => 'Mango Sticky Rice Latte', 'price' => 25000],
            ],
            'Bakso Malang' => [
                ['name' => 'Bakso Komplit', 'price' => 15000],
                ['name' => 'Bakso Halus Besar', 'price' => 4000],
                ['name' => 'Bakso Halus Kecil', 'price' => 2000],
                ['name' => 'Bakso Telur Ayam', 'price' => 8000],
                ['name' => 'Bakso Telur Puyuh', 'price' => 3000],
                ['name' => 'Bakso Urat Besar', 'price' => 4000],
                ['name' => 'Bakso Urat Kecil', 'price' => 2000],
                ['name' => 'Bakso Kotak', 'price' => 3000],
                ['name' => 'Tahu Bakso', 'price' => 2500],
                ['name' => 'Bakso Goreng', 'price' => 3000],
                ['name' => 'Mie Kuning Gulung', 'price' => 1500],
                ['name' => 'Mie Putih Gulung', 'price' => 1500],
                ['name' => 'Pangsit Basah', 'price' => 3000],
                ['name' => 'Pangsit Kering', 'price' => 1500],
                ['name' => 'Sawi Hijau', 'price' => 1000],
                ['name' => 'Tetelan', 'price' => 6000],
                ['name' => 'Lontong', 'price' => 2000],
            ],
            'Mie Ayam' => [
                ['name' => 'Mie Ayam Biasa', 'price' => 12000],
                ['name' => 'Mie Ayam Bakso', 'price' => 15000],
                ['name' => 'Mie Ayam Ceker', 'price' => 15000],
                ['name' => 'Mie Ayam Spesial', 'price' => 20000],
            ],
            'Indomie Menu' => [
                ['name' => 'Indomie Goreng', 'price' => 7000],
                ['name' => 'Indomie Kuah', 'price' => 7000],
                ['name' => 'Bakso Ikan', 'price' => 1500],
                ['name' => 'Cabe', 'price' => 1000],
                ['name' => 'Sawi Hijau', 'price' => 1000],
                ['name' => 'Sosis', 'price' => 2500],
                ['name' => 'Poached Egg/Goreng', 'price' => 4000],
                ['name' => 'Bakso Sapi', 'price' => 2500],
            ],
            'Snack' => [
                ['name' => 'Panchos', 'price' => 13000],
                ['name' => 'Maitos', 'price' => 12000],
                ['name' => 'Happy Tos', 'price' => 11500],
                ['name' => 'Garuda Corn', 'price' => 12000],
                ['name' => 'Chitato Lite', 'price' => 13000],
                ['name' => 'Pota Bee', 'price' => 11000],
                ['name' => 'Taro', 'price' => 10500],
                ['name' => 'Taro 32 gr', 'price' => 5500],
                ['name' => 'Pocky All Varian', 'price' => 10000],
                ['name' => 'Kalpa', 'price' => 2500],
                ['name' => 'Mentos Mint', 'price' => 10000],
                ['name' => 'Mentos Rainbow', 'price' => 10000],
                ['name' => 'Pillows', 'price' => 15000],
                ['name' => 'Sponge', 'price' => 15000],
                ['name' => 'Samax Ring', 'price' => 6000],
                ['name' => 'Momogi 12 gr', 'price' => 1000],
                ['name' => 'Momogi 4,5 gr', 'price' => 1000],
                ['name' => 'Siip', 'price' => 1000],
                ['name' => 'Biskuit Bolu', 'price' => 2000],
                ['name' => 'Oreo Soft Cake', 'price' => 2000],
                ['name' => 'Oreo Isi 3', 'price' => 2000],
            ],
            'Minuman' => [
                ['name' => 'Floridina', 'price' => 5000],
                ['name' => 'Iso Plus', 'price' => 5000],
                ['name' => 'Nu Green Tea', 'price' => 7000],
                ['name' => 'Buah Potong', 'price' => 15000],
                ['name' => 'Salad Buah', 'price' => 18000],
                ['name' => 'Nu Milk Tea', 'price' => 9000],
                ['name' => 'Ichitan', 'price' => 10000],
                ['name' => 'You C 1000', 'price' => 10000],
                ['name' => 'Yakult', 'price' => 2500],
            ],
            'Drink Corner' => [
                ['name' => 'Juice Naga', 'price' => 10000],
                ['name' => 'Juice Alpukat', 'price' => 10000],
                ['name' => 'Juice Mangga', 'price' => 10000],
                ['name' => 'Juice Jeruk Baby', 'price' => 10000],
                ['name' => 'Juice Apel', 'price' => 10000],
                ['name' => 'Juice Strawberry', 'price' => 10000],
                ['name' => 'Juice Semangka', 'price' => 10000],
                ['name' => 'Juice Melon', 'price' => 10000],
                ['name' => 'Juice Jambu', 'price' => 10000],
                ['name' => 'Juice Mix Strawberry Naga', 'price' => 11000],
                ['name' => 'Juice Mix Naga Nanas', 'price' => 11000],
                ['name' => 'Juice Sirsak', 'price' => 10000],
                ['name' => 'Milkshake Chocobanana', 'price' => 15000],
                ['name' => 'Milkshake Coklat', 'price' => 15000],
                ['name' => 'Milkshake Green Tea', 'price' => 15000],
                ['name' => 'Milkshake Oreo', 'price' => 15000],
                ['name' => 'Milkshake Pisang', 'price' => 15000],
                ['name' => 'Milkshake Strawberry', 'price' => 15000],
                ['name' => 'Milkshake Taro', 'price' => 15000],
                ['name' => 'Milkshake Milky Yakult Orange', 'price' => 14000],
                ['name' => 'Milkshake Milky Yakult Strawberry', 'price' => 14000],
                ['name' => 'Squash Lemon', 'price' => 14000],
                ['name' => 'Squash Leci', 'price' => 14000],
                ['name' => 'Squash Anggur', 'price' => 14000],
                ['name' => 'Squash Strawberry', 'price' => 14000],
                ['name' => 'Es Jeruk', 'price' => 5000],
                ['name' => 'Es Kelapa', 'price' => 12000],
                ['name' => 'Es Coklat', 'price' => 12000],
                ['name' => 'Es Teh', 'price' => 5000],
                ['name' => 'Es Teler', 'price' => 12000],
                ['name' => 'Lemon Tea', 'price' => 15000],
                ['name' => 'Lychee Tea', 'price' => 8000],
                ['name' => 'Es Batu', 'price' => 1000],
                ['name' => 'Es Batu Kecil', 'price' => 2000],
            ],
            'Pastry' => [
                ['name' => 'Apem', 'price' => 2500],
                ['name' => 'Arem-arem special', 'price' => 4500],
                ['name' => 'Arem-arem tempe', 'price' => 2500],
                ['name' => 'Arem-arem ayam', 'price' => 3500],
                ['name' => 'Banana cake', 'price' => 5000],
                ['name' => 'Bika Ambon', 'price' => 3000],
                ['name' => 'Bika caramel', 'price' => 3000],
                ['name' => 'Black forest', 'price' => 3500],
                ['name' => 'Bolen chocolate', 'price' => 4500],
                ['name' => 'Bolen cheese', 'price' => 4500],
                ['name' => 'Bolu kukus', 'price' => 2500],
                ['name' => 'Bolu kukus mini', 'price' => 2000],
                ['name' => 'Brownies choco pandan', 'price' => 4000],
                ['name' => 'Brownies choco', 'price' => 3000],
                ['name' => 'Brownies fudgy', 'price' => 4000],
                ['name' => 'Bugis ketan hitam', 'price' => 3000],
                ['name' => 'Bugis mandi', 'price' => 4000],
                ['name' => 'Butter cake', 'price' => 4000],
                ['name' => 'Cake klepon size', 'price' => 4000],
                ['name' => 'Carabika', 'price' => 2500],
                ['name' => 'Carang gesing', 'price' => 4000],
                ['name' => 'Casava', 'price' => 4000],
                ['name' => 'Chicken sus', 'price' => 5000],
                ['name' => 'Dadar gulung', 'price' => 2500],
                ['name' => 'Dadar pisang', 'price' => 3000],
                ['name' => 'Eclair', 'price' => 5000],
                ['name' => 'Eclair mini', 'price' => 3500],
                ['name' => 'Eggroll', 'price' => 6000],
                ['name' => 'Fruty sus / sus buah', 'price' => 5000],
                ['name' => 'Getuk lindri', 'price' => 2000],
                ['name' => 'Jadah manten', 'price' => 3500],
                ['name' => 'Cantik manis', 'price' => 2500],
                ['name' => 'Jasuke', 'price' => 4000],
                ['name' => 'Kacamata', 'price' => 4000],
                ['name' => 'Ketan / talam srikaya', 'price' => 4500],
                ['name' => 'Ketan serundeng', 'price' => 3500],
                ['name' => 'Kimbab', 'price' => 6000],
                ['name' => 'Kipo', 'price' => 3500],
                ['name' => 'Klappertart', 'price' => 4500],
                ['name' => 'Klappertart pngg', 'price' => 4000],
                ['name' => 'Klepon', 'price' => 2500],
                ['name' => 'Krakers tape', 'price' => 3500],
                ['name' => 'Krakers roguth', 'price' => 3500],
                ['name' => 'Kroket', 'price' => 3000],
                ['name' => 'Kroket special', 'price' => 4500],
                ['name' => 'Kue cucur', 'price' => 3000],
                ['name' => 'Kue lumpur', 'price' => 2500],
                ['name' => 'Kueku', 'price' => 2500],
                ['name' => 'Lakut', 'price' => 4000],
                ['name' => 'Lapis kukus warna', 'price' => 3000],
                ['name' => 'Lapis Surabaya', 'price' => 4500],
                ['name' => 'Lasagna', 'price' => 7500],
                ['name' => 'Legomoro', 'price' => 4000],
                ['name' => 'Lemper ayam', 'price' => 3000],
                ['name' => 'Lemper ayam bakar', 'price' => 3500],
                ['name' => 'Lemper ayam kukus', 'price' => 3500],
                ['name' => 'Lemper ayam special', 'price' => 3500],
                ['name' => 'Lepet jagung', 'price' => 3500],
                ['name' => 'Lumpia ayam', 'price' => 3000],
                ['name' => 'Lumpia sayur', 'price' => 2500],
                ['name' => 'Lumpia krenyes', 'price' => 2500],
                ['name' => 'Lumpia special', 'price' => 3500],
                ['name' => 'Lupis', 'price' => 2500],
                ['name' => 'Madusari keju', 'price' => 2500],
                ['name' => 'Makaroni schotel', 'price' => 4000],
                ['name' => 'Makaroni schotel mini', 'price' => 2500],
                ['name' => 'Lapis Mandarin', 'price' => 4500],
                ['name' => 'Martabak ayam', 'price' => 3000],
                ['name' => 'Martabak manis mini', 'price' => 3000],
                ['name' => 'Martabak sayur', 'price' => 2500],
                ['name' => 'Martabak sayur special', 'price' => 3000],
                ['name' => 'Misoa', 'price' => 3500],
                ['name' => 'Moci', 'price' => 2000],
                ['name' => 'Nagasari bandung', 'price' => 3000],
                ['name' => 'Onde-onde', 'price' => 3000],
                ['name' => 'Ongol-ongol', 'price' => 4500],
                ['name' => 'Onigiri', 'price' => 7000],
                ['name' => 'Pandan roll cake', 'price' => 4000],
                ['name' => 'Panekuk coklat', 'price' => 3500],
                ['name' => 'Panekuk vanilla', 'price' => 3000],
                ['name' => 'Pastel ayam', 'price' => 4500],
                ['name' => 'Pastel roguth/sayur', 'price' => 3500],
                ['name' => 'Pie buah', 'price' => 3500],
                ['name' => 'Pie choco', 'price' => 4000],
                ['name' => 'Pie brownies', 'price' => 4000],
                ['name' => 'Pie nanas', 'price' => 4000],
                ['name' => 'Piscok crispy', 'price' => 3500],
                ['name' => 'Pisang goreng caramel', 'price' => 3500],
                ['name' => 'Poll pisang', 'price' => 4000],
                ['name' => 'Poll tape', 'price' => 5000],
                ['name' => 'Puding buah', 'price' => 5000],
                ['name' => 'Puding buah mini', 'price' => 3000],
                ['name' => 'Puding buah special', 'price' => 6000],
                ['name' => 'Puding coklat', 'price' => 4000],
                ['name' => 'Puding coklat mini', 'price' => 3000],
                ['name' => 'Puding jeruk', 'price' => 5000],
                ['name' => 'Puding mangga', 'price' => 5000],
                ['name' => 'Puding Oreo', 'price' => 5500],
                ['name' => 'Puding pandan santan', 'price' => 5000],
                ['name' => 'Puding peach', 'price' => 6000],
                ['name' => 'Puding roti', 'price' => 4500],
                ['name' => 'Puding santan mini', 'price' => 2500],
                ['name' => 'Puding coklat vanilla', 'price' => 5500],
                ['name' => 'Putri mandi', 'price' => 3000],
                ['name' => 'Putu ayu', 'price' => 2500],
                ['name' => 'Rainbow roll cake', 'price' => 4000],
                ['name' => 'Red Velvet roll cake', 'price' => 4000],
                ['name' => 'Risol mayo', 'price' => 3000],
                ['name' => 'Risol ayam', 'price' => 3000],
                ['name' => 'Risol roguth/sayur', 'price' => 3000],
                ['name' => 'Resoles special', 'price' => 3500],
                ['name' => 'Roll cake pandan', 'price' => 4000],
                ['name' => 'Sandwich sosis - konsi', 'price' => 8000],
                ['name' => 'Sandwich beef - konsi', 'price' => 9000],
                ['name' => 'Sandwich sosis - boga', 'price' => 9000],
                ['name' => 'Sate bakso pedas', 'price' => 3500],
                ['name' => 'Sate pentol pedas', 'price' => 3000],
                ['name' => 'Sawit singkong', 'price' => 2500],
                ['name' => 'Semar mendem', 'price' => 3000],
                ['name' => 'Sempol', 'price' => 3000],
                ['name' => 'Sengkulun', 'price' => 4000],
                ['name' => 'Sentiling', 'price' => 4000],
                ['name' => 'Serabi kocor', 'price' => 3500],
                ['name' => 'Serabi solo', 'price' => 2500],
                ['name' => 'Singkong keju', 'price' => 4500],
                ['name' => 'Songgo buono', 'price' => 8500],
                ['name' => 'Sosis solo', 'price' => 3500],
                ['name' => 'Sosis solo basah', 'price' => 3500],
                ['name' => 'Sus choco', 'price' => 4000],
                ['name' => 'Sus mini', 'price' => 3000],
                ['name' => 'Sus roguth', 'price' => 3500],
                ['name' => 'Sus vanilla', 'price' => 4000],
                ['name' => 'Sus topping', 'price' => 5000],
                ['name' => 'Sus buah', 'price' => 5000],
                ['name' => 'Tahu bakso', 'price' => 3500],
                ['name' => 'Tahu bakso hemat', 'price' => 3000],
                ['name' => 'Tahu bakso ungaran', 'price' => 4000],
                ['name' => 'Tahu bakso kencong', 'price' => 2500],
                ['name' => 'Tahu walik', 'price' => 3500],
                ['name' => 'Tahu cetak T. puyuh', 'price' => 3000],
                ['name' => 'Tahu cetak biasa', 'price' => 2000],
                ['name' => 'Tahu isi special', 'price' => 3000],
                ['name' => 'Tahu isi sayur', 'price' => 2000],
                ['name' => 'Talam pandan', 'price' => 2000],
                ['name' => 'Talam ubi ungu', 'price' => 3500],
                ['name' => 'Wajik', 'price' => 2500],
                ['name' => 'Zebra roll cake', 'price' => 4000],
                ['name' => 'Roti Sosis', 'price' => 6000],
            ],
        ];

        foreach ($data as $categoryName => $menus) {
            $category = Category::firstOrCreate(['name' => $categoryName]);
            $template = self::CATEGORY_TEMPLATE_MAP[$categoryName] ?? null;

            foreach ($menus as $menu) {
                Menu::updateOrCreate(
                    ['name' => $menu['name'], 'category_id' => $category->id],
                    ['price' => $menu['price'], 'template' => $template]
                );
            }
        }
    }
}
